# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 20:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='gid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='groupname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uid',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1000)]),
        ),
    ]
