# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20161105_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='service',
            field=models.BooleanField(default=False),
        ),
    ]
