# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20161106_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='superuser',
        ),
    ]
