# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_token',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
