# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20161215_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
