# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-21 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='staff',
        ),
    ]
