# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-25 13:52
from __future__ import unicode_literals

from django.db import migrations


def add_director_group(apps, schema_editor):
    User = apps.get_model("users", "User")
    Group = apps.get_model("users", "Group")
    if not Group.objects.filter(name="director").exists():
        Group.objects.create(id=1337, service=True, name="director")
        Group.objects.get(id=1337).users.add(*User.objects.all())


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20170221_2003'),
    ]

    operations = [
        migrations.RunPython(add_director_group),
    ]
