# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siterequest',
            name='admin_approval',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='siterequest',
            name='teacher_approval',
            field=models.NullBooleanField(default=None),
        ),
    ]
