# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 23:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Website',
            new_name='Site',
        ),
    ]
