# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_auto_20161105_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='category',
            field=models.CharField(choices=[('static', 'static'), ('php', 'php'), ('dynamic', 'dynamic')], max_length=16),
        ),
        migrations.AlterField(
            model_name='site',
            name='purpose',
            field=models.CharField(choices=[('legacy', 'legacy'), ('user', 'user'), ('activity', 'activity')], max_length=16),
        ),
    ]
