# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_auto_20161107_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
