# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_auto_20161119_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='purpose',
            field=models.CharField(choices=[('legacy', 'legacy'), ('user', 'user'), ('activity', 'activity'), ('other', 'other')], max_length=16),
        ),
    ]
