# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_auto_20161119_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='category',
            field=models.CharField(choices=[('static', 'Static'), ('php', 'PHP'), ('dynamic', 'Dynamic')], max_length=16),
        ),
        migrations.AlterField(
            model_name='site',
            name='purpose',
            field=models.CharField(choices=[('legacy', 'Legacy'), ('user', 'User'), ('activity', 'Activity'), ('other', 'Other')], max_length=16),
        ),
    ]
