# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0009_database'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='category',
            field=models.CharField(choices=[('static', 'Static'), ('php', 'PHP'), ('dynamic', 'Dynamic'), ('vm', 'Virtual Machine')], max_length=16),
        ),
    ]
