# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-19 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0011_siterequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siterequest',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='siterequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='SiteRequest',
        ),
    ]
