# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-07 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0012_auto_20170219_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='repo_path',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
