# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-29 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0013_site_repo_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='site',
            old_name='domain',
            new_name='domain_old',
        ),
        migrations.AddField(
            model_name='domain',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
    ]
