# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0016_remove_site_domain_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='purpose',
            field=models.CharField(choices=[('legacy', 'Legacy'), ('user', 'User'), ('project', 'Project'), ('activity', 'Activity'), ('other', 'Other')], max_length=16),
        ),
    ]
