# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0019_settings_to_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='category',
        ),
        migrations.AlterField(
            model_name='database',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.DatabaseHost'),
        ),
    ]
