# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    SiteHost = apps.get_model("sites", "SiteHost")
    Site = apps.get_model("sites", "Site")

    host, created = SiteHost.objects.get_or_create(hostname="director.tjhsst.edu")

    for site in Site.objects.filter(host__isnull=True):
        site.host = host
        site.save()


def reverse_func(apps, schema_editor):
    SiteHost = apps.get_model("sites", "SiteHost")
    Site = apps.get_model("sites", "Site")

    for site in Site.objects.filter(host__isnull=False):
        site.host = None
        site.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0020_auto_20170818_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.SiteHost'),
        ),
        migrations.RunPython(forwards_func, reverse_func)
    ]
