# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0021_auto_20170821_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.SiteHost'),
        ),
    ]
