# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 00:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='users',
            field=models.ManyToManyField(related_name='vms', to=settings.AUTH_USER_MODEL),
        ),
    ]
