# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0002_auto_20161203_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='name',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
