# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0003_auto_20161203_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
