# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0005_virtualmachine_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
