# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 19:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vms', '0007_virtualmachine_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
