# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0009_virtualmachinehost'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vms.VirtualMachineHost'),
        ),
    ]
