# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0011_link_host_to_vms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vms.VirtualMachineHost'),
        ),
    ]
