# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-24 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0013_auto_20180309_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualmachine',
            name='password',
        ),
    ]
