# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-26 02:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0015_virtualmachine_template'),
    ]

    operations = [
        migrations.RenameField(
            model_name='virtualmachine',
            old_name='template',
            new_name='is_template',
        ),
    ]
