# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_historicalarticle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tag',
            new_name='tags',
        ),
        migrations.AlterField(
            model_name='article',
            name='posted',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='posted',
            field=models.DateField(db_index=True),
        ),
    ]
