# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_auto_20170718_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='published',
        ),
        migrations.RemoveField(
            model_name='historicalarticle',
            name='published',
        ),
    ]
