# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_auto_20170718_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='article',
            name='posted',
        ),
        migrations.RemoveField(
            model_name='historicalarticle',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='historicalarticle',
            name='posted',
        ),
        migrations.AddField(
            model_name='article',
            name='publish_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalarticle',
            name='publish_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
